name: test
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip

  # Additional dependency
  - xtb
  - parmed
  - scipy
  - numpy
  - ase
  - matplotlib
  - seaborn
  - networkx
  - pulp<2.2
  - numba>=0.50

    # Testing
  - pytest
  - pytest-cov
  - codecov

