name: qforce
channels:
  - conda-forge
dependencies:
  - geometric>=0.9.7
  - ndcctools
  - numpy>=1.11
  - xtb
  - scipy
  - numpy
  - ase
  - matplotlib
  - seaborn
  - networkx
  - pulp<2.2
  - numba>=0.50
  - parmed
  - pip:
     - pycolt>=0.5.3

